on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching any tag format, i.e. 1.0, 20.15.1

name: Upload Release Asset

env:
  PLUGIN_NAME: logseq-rename-page-shortcut

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.3
      - name: Build project
        id: build
        run: |
          BUILD_TAG=$(git tag --sort version:refname | tail -n 1)
          echo "BUILD_TAG=$BUILD_TAG" >> $GITHUB_ENV
          npm install
          npm run build
          mkdir ${{ env.PLUGIN_NAME }}
          cp LICENSE README.md package.json icon.png ${{ env.PLUGIN_NAME }}/.
          mv dist ${{ env.PLUGIN_NAME }}/.
          zip -r ${{ env.PLUGIN_NAME }}-${BUILD_TAG}.zip ${{ env.PLUGIN_NAME }}
          ls
      - uses: ncipollo/release-action@v1
        with:
          artifactErrorsFailBuild: true
          artifacts: "${{ env.PLUGIN_NAME }}-${{ env.BUILD_TAG }}.zip,package.json"
